### ISSUE TITLE
Unmaintained plugins?

### ISSUE THREAD

**Issue by bfrg** [saccarosium/awesome-vim9#13]
Just FYI: Not sure what your criteria are but all my vim9script plugins in your list are still maintained. Just because a repository hasn't been updated in a few months (or years) doesn't mean that it's not maintained anymore. If a plugin is feature-complete and there are no known bugs to me or anyone else there just won't be any updates. I use most of them daily and when I encounter an issue I fix it. Unless the repository is archived it's still maintained.

**Comment by saccarosium** [comment]
Hi,
my criteria usually is last commit, issues and PRs.
But yes you are correct it isn't always the case that this metrics are correlated with a plugin been unmaintained. 
I will update your plugins.
