### ISSUE TITLE
vim wiki

### ISSUE THREAD

**Issue by Konfekt** [saccarosium/awesome-vim9#16]
As mentioned in the [key note](https://youtu.be/bopbmRyHQog?si=WAcmx9wbC-83zsym), Vim9script could get more attention, with `lsp`,`fuzzyy` or `vimsuggest` and many more being great plug-ins few heard of; how about adding it to the Vim wiki for greater exposure as a first step (while the [new homepage](https://groups.google.com/g/vim_announce/c/cUzmP2xxecM) isn't there yet)?

**Comment by saccarosium** [comment]
I'm sorry I not understanding what you are trying to say? Could you please reformulate?

**Comment by Konfekt** [comment]
Okay, thank you I added [them](https://github.com/vim/vim/wiki/Vim9-Plugins); It's a pity to hear you leaving, they're not many pushing Vim9 forward and I am still not convinced that luascript is a better domain-specific fit, just setting up [a simple mapping]https://github.com/stevearc/oil.nvim?tab=readme-ov-file#quick-start)  reads rather verbose.

**Comment by Konfekt** [comment]
Rather than being sad, I want to thank you for all your contributions, that was much appreciated, and who knows if there'll be a second coming.
